#!/bin/bash

function RunTest()
{
	echo ">> running test '$1'"
	./$1 &> "$1.log"
	code="$?"

	case  "$code" in
		"0")
			echo "    PASS"
			;;
		"77")
			echo "    SKIPPED, details in '$1.log'"
			;;
		*)
			echo "    FAILED (code $code), details in '$1.log'"
			;;
	esac
}

#----------------------------------------------------------------------------------------------------

# set up environment
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`pwd`/../lib

# run all tests
RunTest "test1"
RunTest "test2"
RunTest "test3"
RunTest "test4"
