#!/bin/bash

function RunTest()
{
	echo ">> running test '$1'"
	../$1 &> "$1.log"
	code="$?"

	case  "$code" in
		"0")
			echo "    PASS"
			;;
		"77")
			echo "    SKIPPED, details in '$1.log'"
			;;
		*)
			echo "    FAILED (code $code), details in '$1.log'"
			;;
	esac
}

#----------------------------------------------------------------------------------------------------

# set up environment
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`pwd`/../lib

#----------------------------------------------------------------------------------------------------

# determine ROOT executable

root_exe=`which "root"`
if [ -z "$root_exe" ]
then
	root_exe=`which "root.exe"`
fi

if [ -z "$root_exe" ]
then
	echo "ERROR: Cannot determine ROOT executable. No tests will be run."
	exit 1
fi

export root_exe=$root_exe

#----------------------------------------------------------------------------------------------------
# directory with executables

export bin_dir="../../build/utilities"

#----------------------------------------------------------------------------------------------------
# prepare test directory

mkdir -p "tests"
cd "tests" || exit 2

#----------------------------------------------------------------------------------------------------

# run all tests
RunTest "test1"
RunTest "test2"
RunTest "test3"
RunTest "test4"
