#!/bin/bash

# test for root
which "root" &> /dev/null
if [ $? -ne 0 ]
then
	echo "ERROR: cannot run 'root'."	
	exit 77
fi

# run sampler
../bin/ElegentTDistributionSampler\
	-energy 7000 -pp -models "petrov (3p) [02]" -output "t-distribution_test.root"\
	-model-N 20 -model-tmax 20\
	-full-N 10 -full-tmax 10\
	-lowt-N 10 -lowt-tmax 1\
		|| exit 1

# check output
root -b -q -l 'check_graph_points.cc("t-distribution_test.root", "full range/petrov (3p) [02]/PH/amplitude_re", 10)'
if [ $? -ne 0 ]
then
	echo "ERROR: wrong number of points."
	exit 2
fi

# succes
exit 0
