#!/bin/bash

# run sampler
"$bin_dir/ElegentSDistributionSampler"\
	-pp -models "petrov (3p) [02]" -output "s-distribution_test.root"\
	-N 100 -Wmin 2 -Wmax "1E5"\
		|| exit 1

# check output
$root_exe -b -q -l 'check_graph_points.cc("s-distribution_test.root", "petrov (3p) [02]/si_tot", 100)'
if [ $? -ne 0 ]
then
	echo "ERROR: wrong number of points."
	exit 2
fi

# succes
exit 0
