sudo: required

services:
  - docker

env:
  - DOCKER_IMAGE=jkaspar/for_elegent_cern_cc7:2017_04_27
  - DOCKER_IMAGE=jkaspar/for_elegent_archlinux:2017_04_27

language: bash

before_install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -it $DOCKER_IMAGE /bin/sh -c "git clone https://github.com/jan-kaspar/elegent.git; cd elegent; bash -e travis_test.sh"

notifications:
  email:
    - jan.kaspar@gmail.com
