#!/bin/bash

function Generate()
{
	local mode="$1"
	local energy="$2"

	echo ">> Generate: mode = $mode, sqrt(s) = $energy GeV"

	tag="b-distributions,${mode},${energy}GeV"

	generator="../bin/ElegentBDistributionSampler"
	$generator "-$mode" -energy "$energy" -output "$tag.root" &> "$tag.log"

	tar czf "$tag.tar.gz" "$tag.root" "$tag.log"

	#rm "$tag.root"
	#rm "$tag.log"
}

#----------------------------------------------------------------------------------------------------

Generate "pp" "2760" &
Generate "pp" "7000" &
Generate "pp" "8000" &
Generate "pp" "13000" &
Generate "pp" "14000" &
