#!/bin/bash

function Generate()
{
	local mode="$1"
	local energy="$2"

	echo ">> Generate: mode = $mode, sqrt(s) = $energy GeV"

	tag="t-distributions,${mode},${energy}GeV"

	generator="../bin/ElegentTDistributionSampler"
	models="block [06];bourrely [03];islam (hp) [06,09];islam (lxg) [06,09];jenkovszky [11];petrov (2p) [02];petrov (3p) [02]"
	$generator "-$mode" -energy "$energy" -output "$tag.root" -models "$models" &> "$tag.log"

	tar czf "$tag.tar.gz" "$tag.root" "$tag.log"

	#rm "$tag.root"
	#rm "$tag.log"
}

#----------------------------------------------------------------------------------------------------

Generate "pp" "2760" &
Generate "pp" "7000" &
Generate "pp" "8000" &
Generate "pp" "13000" &
Generate "pp" "14000" &
